<a href="https://colab.research.google.com/github/man0045/Natural_Language_Processing/blob/main/RNN_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
docs = ['recurrent neural network', 'neural network',
        'artificial neural',
        'connection between nodes',
        'can create a cycle',
        'allowing output',
        'some needs to affect subsequent',
        'exhibit temporal',
        'dynamic behavior',
        'affect subsequent']

In [8]:
!pip install tensorflow
!pip install keras

In [11]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer  # <-- Use tensorflow.keras

tokenizer = Tokenizer(oov_token='<nothing>')

In [12]:
tokenizer.fit_on_texts(docs)

In [13]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'affect': 4,
 'subsequent': 5,
 'recurrent': 6,
 'artificial': 7,
 'connection': 8,
 'between': 9,
 'nodes': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'needs': 18,
 'to': 19,
 'exhibit': 20,
 'temporal': 21,
 'dynamic': 22,
 'behavior': 23}

In [14]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 3),
             ('network', 2),
             ('artificial', 1),
             ('connection', 1),
             ('between', 1),
             ('nodes', 1),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('needs', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1)])

In [15]:
tokenizer.document_count

10

In [17]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[6, 2, 3],
 [2, 3],
 [7, 2],
 [8, 9, 10],
 [11, 12, 13, 14],
 [15, 16],
 [17, 18, 19, 4, 5],
 [20, 21],
 [22, 23],
 [4, 5]]

In [19]:
from keras.utils import pad_sequences
nsequence = pad_sequences(sequences, maxlen = 5, padding = 'pre')

nsequence

array([[ 0,  0,  6,  2,  3],
       [ 0,  0,  0,  2,  3],
       [ 0,  0,  0,  7,  2],
       [ 0,  0,  8,  9, 10],
       [ 0, 11, 12, 13, 14],
       [ 0,  0,  0, 15, 16],
       [17, 18, 19,  4,  5],
       [ 0,  0,  0, 20, 21],
       [ 0,  0,  0, 22, 23],
       [ 0,  0,  0,  4,  5]], dtype=int32)

In [20]:
from keras.datasets import imdb

In [21]:
imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [22]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [23]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [24]:
print(len(X_train[0]))

218


In [25]:
from keras.utils import pad_sequences
X_train = pad_sequences(X_train, maxlen = 500, padding = 'post')
X_test = pad_sequences(X_test, maxlen = 500, padding = 'post')

In [26]:
X_train[0]

array([    1,    14,    22,    16,    43,   530,   973,  1622,  1385,
          65,   458,  4468,    66,  3941,     4,   173,    36,   256,
           5,    25,   100,    43,   838,   112,    50,   670, 22665,
           9,    35,   480,   284,     5,   150,     4,   172,   112,
         167, 21631,   336,   385,    39,     4,   172,  4536,  1111,
          17,   546,    38,    13,   447,     4,   192,    50,    16,
           6,   147,  2025,    19,    14,    22,     4,  1920,  4613,
         469,     4,    22,    71,    87,    12,    16,    43,   530,
          38,    76,    15,    13,  1247,     4,    22,    17,   515,
          17,    12,    16,   626,    18, 19193,     5,    62,   386,
          12,     8,   316,     8,   106,     5,     4,  2223,  5244,
          16,   480,    66,  3785,    33,     4,   130,    12,    16,
          38,   619,     5,    25,   124,    51,    36,   135,    48,
          25,  1415,    33,     6,    22,    12,   215,    28,    77,
          52,     5,

In [29]:
print(len(X_train[0]))

500


In [30]:
from collections.abc import Sequence
model = Sequential()
model.add(SimpleRNN(32, input_shape = (500, 1), return_sequences = False))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [32]:
model.fit(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 107s 133ms/step - accuracy: 0.4938 - loss: 0.6982 - val_accuracy: 0.5052 - val_loss: 0.6935
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 122s 108ms/step - accuracy: 0.5064 - loss: 0.6936 - val_accuracy: 0.5024 - val_loss: 0.6946
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 84s 107ms/step - accuracy: 0.5089 - loss: 0.6952 - val_accuracy: 0.5002 - val_loss: 0.6933
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 104s 133ms/step - accuracy: 0.5052 - loss: 0.6932 - val_accuracy: 0.5058 - val_loss: 0.6938
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 124s 109ms/step - accuracy: 0.5007 - loss: 0.6934 - val_accuracy: 0.5063 - val_loss: 0.6946


In [34]:
model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 26ms/step


array([[0.46752942],
       [0.46752942],
       [0.51872814],
       ...,
       [0.46752942],
       [0.46752942],
       [0.46752942]], dtype=float32)

In [36]:
print(X_test[0])

[    1   591   202    14    31     6   717    10    10 18142 10698     5
     4   360     7     4   177  5760   394   354     4   123     9  1035
  1035  1035    10    10    13    92   124    89   488  7944   100    28
  1668    14    31    23    27  7479    29   220   468     8   124    14
   286   170     8   157    46     5    27   239    16   179 15387    38
    32    25  7944   451   202    14     6   717     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0   